[build]
builder = "nixpacks"
buildCommand = "cd .. && npm install && npm run build:client"

[deploy]
startCommand = "cd .. && npm run start:client"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
