[build]
builder = "nixpacks"
buildCommand = "bash -c 'cd $(git rev-parse --show-toplevel) && npm install && npm run build:server'"

[deploy]
startCommand = "bash -c 'cd $(git rev-parse --show-toplevel) && npm run start:server'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
